
Description: >
  Udapeople backend stack.
Parameters:
  ID:
    Description: Unigue Identifier.
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub Udapeople-${ID}
      GroupDescription: Allow port 22 and port 3030.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3030
          ToPort: 3030
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9090
          ToPort: 9090
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9100
          ToPort: 9100
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9093
          ToPort: 9093
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: project3 # If you use another key pair name, you should change this value to match.
      # Ubuntu 18 or higher works fine
      ImageId: ami-068663a3c619dd892
      Tags:
        - Key: Name
          Value: !Sub backend-${ID}

Outputs:
  PublicIp:
    Description: Server Public IP
    Value: !GetAtt EC2Instance.PublicIp
    Export:
      Name: !Sub "${ID}-PublicIp" 
